tagsDit = {
    "eastern": "eastern dragon",
    "western": "western dragon",
    "wyvern": "wyvern",
    "serpent": "serpent",
    "hydra": "hydra",
    "amphiptere": "amphiptere",
    "black": "color:black",
    "blue": "color:blue",
    "bronze": "color:bronze",
    "golden": "color:golden",
    "green": "color:green",
    "silver": "color:silver",
    "grey": "color:grey",
    "red": "color:red",
    "white": "color:white",
    "yellow": "color:yellow",
    "rainbow": "color:rainbow",
    "purple": "color:purple",
    "other": "color:other",
    "scblack": "multicolor:black",
    "scblue": "multicolor:blue",
    "scbronze": "cmultiolor:bronze",
    "scgolden": "multicolor:golden",
    "scgreen": "multicolor:green",
    "scsilver": "multicolor:silver",
    "scgrey": "multicolor:grey",
    "scred": "multicolor:red",
    "scwhite": "multicolor:white",
    "scyellow": "multicolor:yellow",
    "scrainbow": "multicolor:rainbow",
    "scpurple": "multicolor:purple",
    "scother": "multicolor:other",
    "safe": "safe",
    "suggestive": "suggestive",
    "questionable": "questionable",
    "explicit": "explicit",
    "solo": "solo",  # more tags
    "photo": "photo",
    "tradArt": "traditional art",
    "animated": "animated",
    "hug": "hug",
    "kissing": "kissing",
    "city": "city",
    "cloud": "cloud",
    "fire": "fire",
    "forest": "forest",
    "mountain": "mountain",
    "night": "night",
    "sea": "sea",
    "sky": "sky",
    "space": "space",
    "stars": "stars",
    "male": "male",
    "female": "female",
    "herm": "herm",
    "breasts": "breasts",
    "feathWings": "feathered wings",
    "humanized": "humanized",
    "furry": "furry",
    "anthro": "anthro",
    "artist needed": "artist needed",
    "source needed": "source needed",
    "human": "human",
    "mlp": "mlp",
    "artist questionable":"artist questionable",
    "useless source url":"useless source url"}


def getFullTageName(tagName):
    return tagsDit[tagName]
